spring.application.name=GoogleLogin

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLINT ID}
spring.security.oauth2.client.registration.google.client-secret=${SECREAT KEY}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google


spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com


